### PR TITLE
Transpiling index.js to target browsers using webpack

### PR DESCRIPTION
**Pull request by schrepfler**
TODO:

- [x] Make sure all of the significant new logic is covered by tests
No new logic.
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by Urigo** [comment]
Thanks for the PR, @schrepfler .
`graphql-subscriptions` is a server side package, and required only for the NodeJS server, which has a built `require` and modules. 

Are you sure that we need this?

**Comment by schrepfler** [comment]
I was under the impression it's needed together with the subscriptions-transport-ws bundle. What are the dependencies for subscriptions-transport-ws and I'll commit a PR only for those?

**Comment by Urigo** [comment]
It's a dependency because `subscriptions-transport-ws` is a package for both client and server. but `graphql-subscriptions` is only loaded for server side.

**Comment by Urigo** [comment]
@schrepfler 
As discussed, I think we got everything you need for your solution. 
Closing for now, let me know if you're still missing anything.

**Pull request closed without merging**
