### PR TITLE
fix(eventEmitterAsyncIterator): wait to add listeners until first call to next()

### PR DESCRIPTION
**Pull request by jedwards1211**
A more conservative fix for #143

### CODE REVIEW

**Comment by jedwards1211** [comment]
Hi maintainers, I forgot that I made mistakes in this change.  I just fixed my changes and added a test to ensure event listeners don't get added before `next()` is called.

**Comment by jedwards1211** [comment]
Is there something wrong with this PR?

**Comment by jedwards1211** [comment]
@helfer @evans @lorensr @stubailo guys, I think it's really important that we get this merged, it's been almost 3 months, and this is a bug fix.

**Comment by jedwards1211** [comment]
hello

**Comment by jedwards1211** [comment]
guys

**Comment by jedwards1211** [comment]
this

**Comment by jedwards1211** [comment]
is

**Comment by jedwards1211** [comment]
**important**

**Comment by jedwards1211** [comment]
we need

**Comment by jedwards1211** [comment]
to get it

**Comment by jedwards1211** [comment]
merged

**Comment by jedwards1211** [comment]
@NeoPhi @helfer do you guys have any reservations about this?  Can we get it merged?  This fixes a major issue.

**Comment by jonbudd** [comment]
@NeoPhi @helfer Can we please get this merged?

**Comment by grantwwu** [comment]
@jedwards1211 I just asked nicely and got maintainership.  I'm with @jonbudd's org, and we're hitting memory leaks in production we suspect are similar to the ones @TimSusa https://github.com/apollographql/graphql-subscriptions/issues/143#issuecomment-415114410 is seeing.

Do you have a preference between this PR and https://github.com/apollographql/graphql-subscriptions/pull/147 ?

Does this PR also fix `withFilter`?

**Comment by jedwards1211** [comment]
In any case we might as well at least go ahead and merge this regardless of whether we ever deprecate `asyncIterator` like I proposed in #147.
This should reduce the possibility of memory leaks from `withFilter`, but as people like @taion have pointed out, there are still cases where `iterable.return()` isn't sufficient to clean up subscriptions.

**Comment by jonbudd** [comment]
Gotcha. Looking at #147, it looks fairly complete to me (though I admit my Javascript knowledge is somewhat flaky 🙂) -  is there any reason it's still marked as a WIP? Is it because it's a breaking change that you were looking for feedback on?

**Comment by grantwwu** [comment]
I've rebased this commit and pushed some other miscellaneous fixes.  One I wanted to address immediately was this `npm run test` output:

```
(node:14006) UnhandledPromiseRejectionWarning: AssertionError: expected {} to be true
    at /Users/grant.wu/foss/graphql-subscriptions/dist/test/tests.js:67:34
(node:14006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14006) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Pull request merged**
