### PR TITLE
fix: installing via git not creating dist

### PR DESCRIPTION
**Pull request by OmgImAlexis**
When installing via GitHub e.g. `npm i github:apollographql/graphql-subscriptions#master` the dist directory isn't created as the prepare script is missing. This add it.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
This is currently blocking me from fully testing https://github.com/apollographql/graphql-subscriptions/pull/209 as I can't install the fork as it doesn't run `compile` on install.

**Comment by OmgImAlexis** [comment]
@glasser this should be good to review.

**Comment by glasser** [comment]
Thanks, see my comment there re my schedule.

**Comment by glasser** [comment]
Would it make more sense to rename the current prepublishOnly script to prepare? Otherwise I think it will compile twice on publish, right?

**Comment by OmgImAlexis** [comment]
I believe it should stay this way.

> As of npm@5, prepublish scripts are deprecated. Use prepare for build steps and prepublishOnly for upload-only. See the deprecation note in npm help scripts for more information.

**Comment by glasser** [comment]
I'm not proposing adding the deprecated `publish` though, just the prepare which I believe is accurately used for both.

I'll give my version a shot and if it doesn't work out then we can try yours later!

**Comment by glasser** [comment]
I merged my version. Let me know if it doesn't solve your problem.

**Pull request merged**
