### PR TITLE
Fix Issue #81 Infinite loop after last unsubscribe in withFilter function

### LINKED ISSUE #81: Infinite loop after last unsubscribe in withFilter function.
I use withFilter to validate payload and got an infinite loop when there are no subscribers left (payload is resolved immediately with `{value: undefined, done: true}`).
```js
const getNextPromise = () => {
        return asyncIterator
          .next()
          .then(payload => Promise.all([
            payload,
            Promise.resolve(filterFn(payload.value, args, context, info)).catch(() => false),
          ]))
          .then(([payload, filterResult]) => {
            if (filterResult === true) {
              return payload;
            }

            // Skip the current value and wait for the next one
            return getNextPromise();
          });
      };
```
This function recursively calls itself even if payload.done is true and it leads to infinite call. Adding check for payload.done before `return getNextPromise();` fixes this problem or am I missing something?

### PR DESCRIPTION
**Pull request by jansenignacio**
Fixes #81 and related to apollographql/subscriptions-transport-ws#189

### CODE REVIEW

**Comment by NeoPhi** [comment]
It would be good to have add a test that fails prior to adding this fix.

**Comment by jansenignacio** [comment]
@NeoPhi can you suggest a way to write a test for this? The steps to reproduce are outlined in this comment: https://github.com/apollographql/subscriptions-transport-ws/issues/189#issuecomment-310724774

**Comment by maktouch** [comment]
@NeoPhi I updated the commit, added the tests first.

**Comment by jansenignacio** [comment]
@maktouch and I have already signed the CLA but the CI still shows that it's failing :(

**Comment by stubailo** [comment]
Confirmed - the CLA has been signed, status failed to update on this PR though.

**Comment by cncolder** [comment]
This pr fix infinite loop bug. But expose another issus in `withFilter`.

Sometime payload value is undefined in `filterFn(payload.value, args, context, info)`. User need check `rootValue` in every filter.

```js
Subscription: {
    serverUpdated: {
      resolve: (rootValue, args, ctx, info) => rootValue,
      subscribe: withFilter(
        () => pubsub.asyncIterator(['serverUpdated']),
        // Check rootValue before use it.
        (rootValue, args, ctx, info) => !!rootValue && rootValue.id === ctx.user.id
      )
    }
}
```

[https://github.com/apollographql/graphql-subscriptions/blob/d8583778db6f408375949e8b34fb70601ff8580d/src/with-filter.ts#L15](https://github.com/apollographql/graphql-subscriptions/blob/d8583778db6f408375949e8b34fb70601ff8580d/src/with-filter.ts#L15)

**Pull request merged**
